//
//  ChannelOpenPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-23.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelOpenPresentationLogic
{
  func presentChannelConfirm(response: ChannelOpen.ChannelConfirm.Response)
}

class ChannelOpenPresenter: ChannelOpenPresentationLogic
{
  weak var viewController: ChannelOpenDisplayLogic?
  
  
  // MARK: Channel Opening Confirm
  
  func presentChannelConfirm(response: ChannelOpen.ChannelConfirm.Response) {
    if response.isPubKeyValid, response.isIPValid, response.isPortValid, response.isFundingValid, response.isInitPayValid {
      viewController?.displayChannelConfirm()
      
    } else {
      let viewModel = ChannelOpen.ChannelConfirm.ErrorVM(errTitle: "Channel Open Error",
                                                         errMsg: "Invalid new channel parameters. Please correct and try again")
      viewController?.displayChannelConfirmError(viewModel: viewModel)
    }
  }
}
