//
//  PasswordCreateRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-17.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PasswordCreateRoutingLogic
{
  func routeToCreateRecover()
}

protocol PasswordCreateDataPassing
{
  var dataStore: PasswordCreateDataStore? { get }
}

class PasswordCreateRouter: NSObject, PasswordCreateRoutingLogic, PasswordCreateDataPassing
{
  weak var viewController: PasswordCreateViewController?
  var dataStore: PasswordCreateDataStore?
  
  // MARK: Routing
  
  func routeToCreateRecover()
  {
    let storyboard = UIStoryboard(name: "CreateRecover", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "CreateRecoverViewController") as! CreateRecoverViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToCreateRecover(source: dataStore!, destination: &destinationDS)
    navigateToCreateRecover(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToCreateRecover(source: PasswordCreateViewController, destination: CreateRecoverViewController)
  {
    source.dismiss(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToCreateRecover(source: PasswordCreateDataStore, destination: inout CreateRecoverDataStore)
  {
    // destination.name = source.name
  }
}
