//
//  AutopilotModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-06-10.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Autopilot {

  enum Constants {
    static let minFundAlloc = 0.2
    static let maxFundAlloc = 1.0
    static let minChannelSize = LNConstants.minChannelSize
    static let maxChannelSize = LNConstants.maxAutoChannelSize
    static let minNumChannels = 0
    static let maxNumChannels = LNConstants.maxAutoChannels
  }
  
  enum ReadConfig {
    struct Request { }
    struct Response {
      var result: Result<LNAutopilotConfig>
    }
    struct ViewModel {
      var active: Bool
      var fundAlloc: Double
      var minChanSize: Bitcoin
      var maxChanSize: Bitcoin
      var maxChanNum: Int
    }
  }
  
  enum WriteConfig {
    struct Request {
      var active: Bool
      var fundAlloc: Double
      var minChanSize: Bitcoin
      var maxChanSize: Bitcoin
      var maxChanNum: Int
    }
    struct Response {
      var result: Result<Void>
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
