//
//  AutopilotInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-06-10.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AutopilotBusinessLogic
{
  func doSomething(request: Autopilot.Something.Request)
}

protocol AutopilotDataStore
{
  //var name: String { get set }
}

class AutopilotInteractor: AutopilotBusinessLogic, AutopilotDataStore
{
  var presenter: AutopilotPresentationLogic?
  var worker: AutopilotWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Autopilot.Something.Request)
  {
    worker = AutopilotWorker()
    worker?.doSomeWork()
    
    let response = Autopilot.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
