//
//  LNDDebugLevelInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LNDDebugLevelBusinessLogic {
  func fetchSubsystems(request: LNDDebugLevel.FetchSubsystems.Request)
}

protocol LNDDebugLevelDataStore {
  //var name: String { get set }
}

class LNDDebugLevelInteractor: LNDDebugLevelBusinessLogic, LNDDebugLevelDataStore {
  var presenter: LNDDebugLevelPresentationLogic?
  var worker: LNDDebugLevelWorker?
  
  
  // MARK: Fetch Subsystems
  
  func fetchSubsystems(request: LNDDebugLevel.FetchSubsystems.Request) {
    LNServices.debugLevel(show: true) { (responder) in
      do {
        let subsystemsString = try responder()
        let subsystemsStrings = subsystemsString.trimmingCharacters(in: .whitespacesAndNewlines).split(separator: " ").map({ return String($0) })
        
        let result = Result<[String]>.success(subsystemsStrings)
        let response = LNDDebugLevel.FetchSubsystems.Response(result: result)
        self.presenter?.presentFetchSubsystems(response: response)
      } catch {
        let result = Result<[String]>.failure(error)
        let response = LNDDebugLevel.FetchSubsystems.Response(result: result)
        self.presenter?.presentFetchSubsystems(response: response)
      }
    }
  }
}
