//
//  LNDLogConsoleInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LNDLogConsoleBusinessLogic
{
  func doSomething(request: LNDLogConsole.Something.Request)
}

protocol LNDLogConsoleDataStore
{
  //var name: String { get set }
}

class LNDLogConsoleInteractor: LNDLogConsoleBusinessLogic, LNDLogConsoleDataStore
{
  var presenter: LNDLogConsolePresentationLogic?
  var worker: LNDLogConsoleWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LNDLogConsole.Something.Request)
  {
    worker = LNDLogConsoleWorker()
    worker?.doSomeWork()
    
    let response = LNDLogConsole.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
