//
//  LNDLogConsolePresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LNDLogConsolePresentationLogic
{
  func presentSomething(response: LNDLogConsole.Something.Response)
}

class LNDLogConsolePresenter: LNDLogConsolePresentationLogic
{
  weak var viewController: LNDLogConsoleDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LNDLogConsole.Something.Response)
  {
    let viewModel = LNDLogConsole.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
