//
//  WalletMainModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WalletMain
{
  // MARK: Update Balances
  
  enum UpdateBalances {
    
    struct Request {
    }
    struct Response {
      var onChainBalance: Bitcoin?
      var channelBalance: Bitcoin?
    }
    struct ViewModel {
      var totalBalanceString: String
      var channelBalanceString: String
    }
    struct ErrorVM {
      var errTitle: String
      var errMsg: String
    }
  }
}
