//
//  WalletMainViewController.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletMainDisplayLogic: class {
  func displayBalances(viewModel: WalletMain.UpdateBalances.ViewModel)
  func displayBalancesError(viewModel: WalletMain.UpdateBalances.ErrorVM)
  
  func updateChannels(viewModel: WalletMain.UpdateChannels.ViewModel)
  func displayChannelsError(viewModel: WalletMain.UpdateChannels.ErrorVM)
  
  func updateTransactions(viewModel: WalletMain.UpdateTransactions.ViewModel)
  func displayTransactionsError(viewModel: WalletMain.UpdateTransactions.ErrorVM)
}


class WalletMainViewController: SLViewController, WalletMainDisplayLogic, UITableViewDelegate, UITableViewDataSource {
  var interactor: WalletMainBusinessLogic?
  var router: (WalletMainRoutingLogic & WalletMainDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = WalletMainInteractor()
    let presenter = WalletMainPresenter()
    let router = WalletMainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  
  // MARK: Local Constants
  
  struct Constants {
    static let txnCellReuseID = "TransactionCell"
    static let chCellReuseID = "ChannelCell"
  }
  
  
  // MARK: IBOutlets
  
  @IBOutlet weak var totalBalanceLabel: UILabel!
  @IBOutlet weak var channelBalanceLabel: UILabel!
  @IBOutlet weak var pagingScrollView: UIScrollView!
  @IBOutlet weak var transactionView: WalletPageView!
  @IBOutlet weak var channelView: WalletPageView!
  
  var updateEventHandle: EventCentral.Handle?
  var syncHandle: EventCentral.Handle?
    
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    // Paging buttons target assignment
    transactionView.chHdrButton.addTarget(self, action: #selector(channelTapped), for: .touchUpInside)
    channelView.txnHdrButton.addTarget(self, action: #selector(transactionTapped), for: .touchUpInside)
    
    // Bottom buttons target assignment
    transactionView.leftButton.addTarget(self, action: #selector(payTapped), for: .touchUpInside)
    transactionView.rightButton.addTarget(self, action:#selector(receiveTapped), for: .touchUpInside)
    channelView.leftButton.addTarget(self, action: #selector(openChannelTapped), for: .touchUpInside)
    
    // Setup Table Views
    setupTransactionTableView()
    setupChannelTableView()
  }
  
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    
    // Check chain for sync
    syncHandle = EventCentral.shared.subscribeToSync { (synced, percentage, date) in
      if synced {
        DispatchQueue.main.async {
          // Enable Pay & Manual Open Channel
          self.transactionView.leftButton.isEnabled = true
          self.transactionView.leftButton.backgroundColor = UIColor.lightAzureBlue
          self.transactionView.leftButton.shadowColor = UIColor.lightAzureBlueShadow
          self.transactionView.leftButton.setTitleColor(UIColor.normalText, for: .normal)
          
          self.channelView.leftButton.isEnabled = true
          self.channelView.leftButton.backgroundColor = UIColor.lightAzureBlue
          self.channelView.leftButton.shadowColor = UIColor.lightAzureBlueShadow
          self.channelView.leftButton.setTitleColor(UIColor.normalText, for: .normal)
        }
        
        // Do an immediate update
        self.updateBalances()
        self.fetchTransactions()
        self.fetchChannels()
        
        // Re-subscribe to events
        self.updateEventHandle = EventCentral.shared.subscribe(to: [.periodicUpdate, .transaction, .openUpdate, .closeUpdate]) { message in
          self.updateBalances()
          
          switch message {
          case .transaction:
            self.fetchTransactions()
            
          case .openUpdate, .closeUpdate:
            self.fetchChannels()
            
          case .periodicUpdate:
            self.fetchTransactions()
            self.fetchChannels()
            
          default:
            SLLog.assert("Do not expect unsubscribed message types")
          }
        }
      } else {
        DispatchQueue.main.async {
          // TODO: Display views in place of Transaction/Channel View
          
          // Disable Pay & Manual Open
          self.transactionView.leftButton.isEnabled = false
          self.transactionView.leftButton.backgroundColor = UIColor.disabledGray
          self.transactionView.leftButton.shadowColor = UIColor.disabledGrayShadow
          self.transactionView.leftButton.setTitleColor(UIColor.disabledText, for: .normal)
          
          self.channelView.leftButton.isEnabled = false
          self.channelView.leftButton.backgroundColor = UIColor.disabledGray
          self.channelView.leftButton.shadowColor = UIColor.disabledGrayShadow
          self.channelView.leftButton.setTitleColor(UIColor.disabledText, for: .normal)
        }
      }
    }
    
    
  }
  
  override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    
    // Unsubscribe from events
    if let handle = updateEventHandle {
      EventCentral.shared.unsubscribe(from: handle)
      updateEventHandle = nil
    }
    
    if let handle = syncHandle {
      EventCentral.shared.unsubscribeFromSync(on: handle)
      syncHandle = nil
    }
  }
  
  
  // MARK: Paging control
  
  @objc private func channelTapped(_ sender: UIButton) {
    pagingScrollView.setContentOffset(CGPoint(x: transactionView.bounds.width, y: 0.0), animated: true)
  }
  
  @objc private func transactionTapped(_ sender: UIButton) {
    pagingScrollView.setContentOffset(CGPoint(x: 0.0, y: 0.0), animated: true)
  }
  
  
  // MARK: Table View Delegates
  
  func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
    switch tableView {
    case transactionView.tableView:
      return TxnTableViewCell.Constants.preferredHeight
      
    case channelView.tableView:
      return ChTableViewCell.Constants.preferredHeight
    
    default:
      SLLog.fatal("Unrecognized Tableview - \(tableView)")
    }
  }
  
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    switch tableView {
    case transactionView.tableView:
      return transactions.count

    case channelView.tableView:
      return channels.count

    default:
      SLLog.fatal("Unrecognized Tableview - \(tableView)")
    }
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    switch tableView {
    case transactionView.tableView:
      return transactionTableView(cellForRowAt: indexPath)
      
    case channelView.tableView:
      return channelTableView(cellForRowAt: indexPath)
      
    default:
      SLLog.fatal("Unrecognized Tableview - \(tableView)")
    }
  }
  
  
  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    switch tableView {
    case transactionView.tableView:
      router?.routeToTransactionDetails(type: transactions[indexPath.row].paymentType,
                                        hash: transactions[indexPath.row].txHash)
    case channelView.tableView:
      router?.routeToChannelDetails(channelPoint: channels[indexPath.row].channelPoint)
    default:
      SLLog.fatal("Unrecognized Tableview - \(tableView)")
    }
  }
  
  
  // MARK: Transactions Table View
  
  var transactions = [WalletMain.UpdateTransactions.Transaction]()
  
  private func setupTransactionTableView() {
    let nib = UINib(nibName: "TxnTableViewCell", bundle: nil)
    transactionView.tableView.register(nib, forCellReuseIdentifier: Constants.txnCellReuseID)
    transactionView.tableView.delegate = self
    transactionView.tableView.dataSource = self
    
    // Add refresh control
    let refreshControl = UIRefreshControl()
    refreshControl.addTarget(self, action: #selector(fetchTransactions), for: .valueChanged)
    refreshControl.tintColor = UIColor.spaceCadetBlue
    transactionView.tableView.refreshControl = refreshControl
  }
  
  private func transactionTableView(cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = transactionView.tableView.dequeueReusableCell(withIdentifier: Constants.txnCellReuseID, for: indexPath) as? TxnTableViewCell else {
      SLLog.fatal("Dequeued cell with identifier \(Constants.txnCellReuseID) not of TxnTableViewCell type")
    }
    
    switch transactions[indexPath.row].paymentType {
    case .lightning:
      cell.payTypeImageView.image = UIImage(named: "BoltColored")
    case .onChain:
      cell.payTypeImageView.image = UIImage(named: "ChainColored")
    }
    
    cell.addressLabel.text = transactions[indexPath.row].address
    cell.statusLabel.text = transactions[indexPath.row].statusText
    cell.statusLabel.textColor = transactions[indexPath.row].statusColor
    cell.dateLabel.text = transactions[indexPath.row].dateText
    cell.amountLabel.text = transactions[indexPath.row].amountText
    cell.feeLabel.text = transactions[indexPath.row].feeText
    
    return cell
  }
  
  @objc private func fetchTransactions() {
    let request = WalletMain.UpdateTransactions.Request()
    interactor?.updateTransactions(request: request)
  }
  
  func updateTransactions(viewModel: WalletMain.UpdateTransactions.ViewModel) {
    transactions = viewModel.transactions
    
    DispatchQueue.main.async {
      self.transactionView.tableView.reloadData()
      if let refreshControl = self.transactionView.tableView.refreshControl, refreshControl.isRefreshing {
        refreshControl.perform(#selector(UIRefreshControl.endRefreshing), with: nil, afterDelay: 0.0)
      }
    }
  }
  
  func displayTransactionsError(viewModel: WalletMain.UpdateTransactions.ErrorVM) {
    let alertDialog = UIAlertController(title: viewModel.errTitle,
                                        message: viewModel.errMsg,
                                        preferredStyle: .alert).addAction(title: "OK", style: .default, handler: nil)
    DispatchQueue.main.async {
      if let refreshControl = self.transactionView.tableView.refreshControl, refreshControl.isRefreshing {
        refreshControl.endRefreshing()
      }
      self.present(alertDialog, animated: true, completion: nil)
    }
  }
  
  
  // MARK: Channels Table View
  
  var channels = [ChannelVM]()
  
  private func setupChannelTableView() {
    let nib = UINib(nibName: "ChTableViewCell", bundle: nil)
    channelView.tableView.register(nib, forCellReuseIdentifier: Constants.chCellReuseID)
    channelView.tableView.delegate = self
    channelView.tableView.dataSource = self
    
    // Add refresh control
    let refreshControl = UIRefreshControl()
    refreshControl.addTarget(self, action: #selector(fetchChannels), for: .valueChanged)
    refreshControl.tintColor = UIColor.spaceCadetBlue
    channelView.tableView.refreshControl = refreshControl
  }
  
  private func channelTableView(cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = channelView.tableView.dequeueReusableCell(withIdentifier: Constants.chCellReuseID, for: indexPath) as? ChTableViewCell else {
      SLLog.fatal("Dequeued cell with identifier \(Constants.chCellReuseID) not of ChTableViewCell type")
    }
    cell.canPayAmountLabel.text = channels[indexPath.row].canPayAmt
    cell.canRcvAmountLabel.text = channels[indexPath.row].canRcvAmt
    cell.nodePubKeyLabel.text = channels[indexPath.row].nodePubKey
    cell.statusLabel.text = channels[indexPath.row].statusText
    cell.statusLabel.textColor = channels[indexPath.row].statusColor
    
    return cell
  }
  
  @objc private func fetchChannels() {
    let request = WalletMain.UpdateChannels.Request()
    interactor?.updateChannels(request: request)
  }
  
  func updateChannels(viewModel: WalletMain.UpdateChannels.ViewModel) {
    channels = viewModel.channels
    
    DispatchQueue.main.async {
      self.channelView.tableView.reloadData()
      
      if let refreshControl = self.channelView.tableView.refreshControl, refreshControl.isRefreshing {
        refreshControl.perform(#selector(UIRefreshControl.endRefreshing), with: nil, afterDelay: 0.0)
      }
    }
  }
  
  func displayChannelsError(viewModel: WalletMain.UpdateChannels.ErrorVM) {
    let alertDialog = UIAlertController(title: viewModel.errTitle,
                                        message: viewModel.errMsg,
                                        preferredStyle: .alert).addAction(title: "OK", style: .default, handler: nil)
    DispatchQueue.main.async {
      if let refreshControl = self.channelView.tableView.refreshControl, refreshControl.isRefreshing {
        refreshControl.endRefreshing()
      }
      self.present(alertDialog, animated: true, completion: nil)
    }
  }
  
  
  // MARK: Pay
  
  @objc private func payTapped(_ sender: SLBarButton) {
    router?.routeToPayMain()
  }
  
  
  // MARK: Receive
  
  @objc private func receiveTapped(_ sender: SLBarButton) {
    router?.routeToReceiveMain()
  }
  
  
  // MARK: Open Channel
  
  @objc private func openChannelTapped(_ sender: SLBarButton) {
    let storyboard = UIStoryboard(name: "ChannelOpen", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChannelOpenViewController") as! ChannelOpenViewController
    navigationController?.pushViewController(destinationVC, animated: true)
  }
  
  
  // MARK: Update Balance
  
  private func updateBalances() {
    let request = WalletMain.UpdateBalances.Request()
    interactor?.updateBalances(request: request)
  }
  
  func displayBalances(viewModel: WalletMain.UpdateBalances.ViewModel) {
    DispatchQueue.main.async {
      self.totalBalanceLabel.text = viewModel.totalBalanceString
      self.channelBalanceLabel.text = viewModel.channelBalanceString
    }
  }
  
  func displayBalancesError(viewModel: WalletMain.UpdateBalances.ErrorVM) {
    let alertDialog = UIAlertController(title: viewModel.errTitle, message: viewModel.errMsg, preferredStyle: .alert).addAction(title: "OK", style: .default)
    
    DispatchQueue.main.async {
      self.present(alertDialog, animated: true, completion: nil)
    }
  }
}
