//
//  WalletMainPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletMainPresentationLogic
{
  func presentUpdatedBalances(response: WalletMain.UpdateBalances.Response)
}

class WalletMainPresenter: WalletMainPresentationLogic {
  weak var viewController: WalletMainDisplayLogic?
  
  // MARK: Update Balances
  
  func presentUpdatedBalances(response: WalletMain.UpdateBalances.Response) {
    
    guard let onChainBalance = response.onChainBalance, let channelBalance = response.channelBalance else {
      let viewModel = WalletMain.UpdateBalances.ErrorVM(errTitle: "Balance Error",
                                                        errMsg: "Cannot get Wallet and Channel Balance. Consider restarting the app to recover")
      viewController?.displayBalancesError(viewModel: viewModel)
      return
    }
    
    let totalBalance = Bitcoin(onChainBalance + channelBalance)
    let totalString = "\(totalBalance.formattedInSatoshis())"
    let channelString = "\(channelBalance.formattedInSatoshis())"
    let viewModel = WalletMain.UpdateBalances.ViewModel(totalBalanceString: totalString,
                                                        channelBalanceString: channelString)
    viewController?.displayBalances(viewModel: viewModel)
  }
}
