//
//  ChannelDetailsPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-04.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelDetailsPresentationLogic
{
  func presentSomething(response: ChannelDetails.Something.Response)
}

class ChannelDetailsPresenter: ChannelDetailsPresentationLogic
{
  weak var viewController: ChannelDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChannelDetails.Something.Response)
  {
    let viewModel = ChannelDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
