//
//  ChannelDetailsInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-04.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelDetailsBusinessLogic
{
  func doSomething(request: ChannelDetails.Something.Request)
}

protocol ChannelDetailsDataStore
{
  //var name: String { get set }
}

class ChannelDetailsInteractor: ChannelDetailsBusinessLogic, ChannelDetailsDataStore
{
  var presenter: ChannelDetailsPresentationLogic?
  var worker: ChannelDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChannelDetails.Something.Request)
  {
    worker = ChannelDetailsWorker()
    worker?.doSomeWork()
    
    let response = ChannelDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
