//
//  ChannelDetailsModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-04.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChannelDetails {
  enum Refresh {
    enum Error: LocalizedError {
      case noChannelInfo
      
      var localizedDescription: String {
        switch self {
        case .noChannelInfo:
          return NSLocalizedString("No Channel Info Supplied", comment: "ChannelDetails.Refresh.Error enum")
        }
      }
    }
    struct Request { }
    struct Response {
      var result: Result<ChannelVM>
    }
    struct ViewModel {
      var channelVM: ChannelVM
      var leftButtonHidden: Bool
      var rightButtonHidden: Bool
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
