//
//  RootInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootBusinessLogic
{
  func checkWalletPresence(request: Root.WalletPresenceRouting.Request)
}

protocol RootDataStore
{
}

class RootInteractor: RootBusinessLogic, RootDataStore
{
  var presenter: RootPresentationLogic?
  
  private var checkRetryRemaining = Root.WalletPresenceRouting.Constants.checkWalletTryCount
  
  func checkWalletPresence(request: Root.WalletPresenceRouting.Request) {
    
    guard checkRetryRemaining > 0 else {
      checkRetryRemaining = Root.WalletPresenceRouting.Constants.checkWalletTryCount
      
      SLLog.warning("Wallet presence check retry exhausted")
      let response = Root.WalletPresenceRouting.Response(walletPresent: nil)
      presenter?.presentWalletPresenceRouting(response: response)
      return
    }
    
    DispatchQueue.global(qos: .background).asyncAfter(deadline: DispatchTime.now() + Root.WalletPresenceRouting.Constants.timeBetweenCheckRetry) {
    
      if self.checkRetryRemaining != Root.WalletPresenceRouting.Constants.checkWalletTryCount {
        SLLog.info("Retrying wallet precense check - \(self.checkRetryRemaining) retries remaining")
      }
      self.checkRetryRemaining -= 1
      
      do {
        try LNServices.unlockWallet(walletPassword: "") { [unowned self] (result) in
          do {
            try result()
          } catch let error as GRPCResultError {
            switch Int32(error.code) {
            case GRPCResultError.StatusCode.unavailable:
              SLLog.verbose("Unlock Wallet Unavailable. Code \(error.code) - \(error.localizedDescription)")
              self.checkWalletPresence(request: request)
              
            case GRPCResultError.StatusCode.unknown:
              
              if error.localizedDescription == "wallet not found"  { // TODO: Is there a less hacky way to do this? Consider doing a feature request to LND.
                SLLog.info("Unlock Wallet Not Found. Code \(error.code) - \(error.localizedDescription)")
                let response = Root.WalletPresenceRouting.Response(walletPresent: false)
                self.presenter?.presentWalletPresenceRouting(response: response)
              }
              else if error.localizedDescription == "invalid passphrase for master public key" {
                SLLog.info("Unlock Wallet Found. Code \(error.code) - \(error.localizedDescription)")
                let response = Root.WalletPresenceRouting.Response(walletPresent: true)
                self.presenter?.presentWalletPresenceRouting(response: response)
              }
              
            default:
              SLLog.debug("Unlock Wallet Result NSError. Code \(error.code) - \(error.localizedDescription)")
              self.checkWalletPresence(request: request)
            }
            
          } catch {
            SLLog.debug("Unlock Wallet Result Generic Error. Code \(error.localizedDescription)")
            self.checkWalletPresence(request: request)
          }
        }
      } catch {
        SLLog.debug("Unlock Wallet Return Error. Code \(error.localizedDescription)")
        self.checkWalletPresence(request: request)
      }
    }
  }
}
