//
//  RootRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RootRoutingLogic
{
  func routeToCreateRecover()
  func routeToUnlockApp()
  func routeToWalletNavigation()
}

protocol RootDataPassing
{
  var dataStore: RootDataStore? { get }
}

class RootRouter: NSObject, RootRoutingLogic, RootDataPassing
{
  weak var viewController: RootViewController?
  var dataStore: RootDataStore?
  
  // MARK: Routing
  
  func routeToCreateRecover()
  {
    let storyboard = UIStoryboard(name: "CreateRecover", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "CreateRecoverViewController") as! CreateRecoverViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToCreateRecover(source: dataStore!, destination: &destinationDS)
    navigateToCreateRecover(source: viewController!, destination: destinationVC)
  }

  func routeToUnlockApp()
  {
    let storyboard = UIStoryboard(name: "UnlockApp", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "UnlockAppViewController") as! UnlockAppViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToUnlockApp(source: dataStore!, destination: &destinationDS)
    navigateToUnlockApp(source: viewController!, destination: destinationVC)
  }
  
  func routeToWalletNavigation() {
    let storyboard = UIStoryboard(name: "WalletNavigation", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "WalletNavigationController") as! WalletNavigationController
    navigateToWalletNavigation(source: viewController!, destination: destinationVC)
  }
  
  
  // MARK: Navigation
  
  func navigateToCreateRecover(source: RootViewController, destination: CreateRecoverViewController) {
    source.present(destination, animated: false, completion: nil)
  }
  
  func navigateToUnlockApp(source: RootViewController, destination: UnlockAppViewController) {
    source.present(destination, animated: false, completion: nil)
  }
  
  func navigateToWalletNavigation(source: RootViewController, destination: WalletNavigationController) {
    source.present(destination, animated: true, completion: nil)
  }
  
  
  // MARK: Passing data
  
  func passDataToCreateRecover(source: RootDataStore, destination: inout CreateRecoverDataStore) {
    // destination.name = source.name
  }
  
  func passDataToUnlockApp(source: RootDataStore, destination: inout UnlockAppDataStore) {
    // destination.name = source.name
  }

}
