//
//  TransactionDetailsModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-08.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TransactionDetails {
  
  enum Error: LocalizedError {
    case noTransactionInput
    case transactionNotFound
    
    var localizedDescription: String {
      switch self {
      case .noTransactionInput:
        return NSLocalizedString("No Transaction Hash in Data Store", comment: "Transaction Details Error enum")
      case .transactionNotFound:
        return NSLocalizedString("Cannot find Transaction for Hash", comment: "Transaction Details Error enum")
      }
    }
  }
  
  enum TxDisplayType {
    case onChainTx(BTCTransaction)
    case lnPayment(LNPayment)
  }
  
  
  // MARK: Refresh
  
  enum Refresh {
    struct Request { }
    struct Response {
      var result: Result<TxDisplayType>
    }
    
    struct ViewModel {
      var txType: BitcoinPaymentType
      var txHeaderText: String
      var txHashTitle: String
      var txHashText: String
      var amountText: String
      var feesText: String
      var dateText: String
      var confirmationsText: String?
      var blockHeightText: String?
      var hashPreimageTitle: String
      var hashPreimageText: String
      var destPathTitle: String
      var destPaths: [String]
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
