//
//  CreateRecoverPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-14.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRecoverPresentationLogic
{
  func presentSomething(response: CreateRecover.Something.Response)
}

class CreateRecoverPresenter: CreateRecoverPresentationLogic
{
  weak var viewController: CreateRecoverDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateRecover.Something.Response)
  {
    let viewModel = CreateRecover.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
