//
//  CreateRecoverRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-14.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateRecoverRoutingLogic
{
  func routeToPasswordCreate()
}

protocol CreateRecoverDataPassing
{
  var dataStore: CreateRecoverDataStore? { get }
}

class CreateRecoverRouter: NSObject, CreateRecoverRoutingLogic, CreateRecoverDataPassing
{
  weak var viewController: CreateRecoverViewController?
  var dataStore: CreateRecoverDataStore?
  
  // MARK: Routing
  
  func routeToPasswordCreate()
  {
    let storyboard = UIStoryboard(name: "PasswordCreate", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "PasswordCreateViewController") as! PasswordCreateViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToPasswordCreate(source: dataStore!, destination: &destinationDS)
    navigateToPasswordCreate(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToPasswordCreate(source: CreateRecoverViewController, destination: PasswordCreateViewController)
  {
    source.present(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToPasswordCreate(source: CreateRecoverDataStore, destination: inout PasswordCreateDataStore)
  {
    // destination.name = source.name
  }
}
