//
//  CreateRecoverViewController.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-14.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRecoverDisplayLogic: class
{
  func displaySomething(viewModel: CreateRecover.Something.ViewModel)
}

class CreateRecoverViewController: SLViewController, CreateRecoverDisplayLogic
{
  var interactor: CreateRecoverBusinessLogic?
  var router: (NSObjectProtocol & CreateRecoverRoutingLogic & CreateRecoverDataPassing)?

  
  // MARK: IBActions
  
  @IBAction func createNewWalletTapped(_ sender: SLBarButton) {
    router?.routeToPasswordCreate()
  }
  
  @IBAction func recoverWalletTapped(_ sender: SLBarButton) {
  }
  
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CreateRecoverInteractor()
    let presenter = CreateRecoverPresenter()
    let router = CreateRecoverRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = CreateRecover.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CreateRecover.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
