//
//  PayConfirmPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-28.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayConfirmPresentationLogic
{
  func presentSomething(response: PayConfirm.Something.Response)
}

class PayConfirmPresenter: PayConfirmPresentationLogic
{
  weak var viewController: PayConfirmDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PayConfirm.Something.Response)
  {
    let viewModel = PayConfirm.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
