//
//  ReceiveMainRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-21.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ReceiveMainRoutingLogic
{
  func routeToWalletMain()
}

protocol ReceiveMainDataPassing
{
  var dataStore: ReceiveMainDataStore? { get }
}

class ReceiveMainRouter: NSObject, ReceiveMainRoutingLogic, ReceiveMainDataPassing
{
  weak var viewController: ReceiveMainViewController?
  var dataStore: ReceiveMainDataStore?
  
  
  // MARK: Routing
  
  func routeToWalletMain()
  {
    let storyboard = UIStoryboard(name: "WalletNavigation", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "WalletMainViewController") as! WalletMainViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToWalletMain(source: dataStore!, destination: &destinationDS)
    navigateToWalletMain(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToWalletMain(source: ReceiveMainViewController, destination: WalletMainViewController)
  {
    guard let navigationController = source.navigationController else {
      SLLog.assert("\(type(of: source)).navigationController = nil")
      return
    }
    navigationController.popViewController(animated: true)
  }
  
  
  // MARK: Passing data
  
  func passDataToWalletMain(source: ReceiveMainDataStore, destination: inout WalletMainDataStore)
  {
    // destination.name = source.name
  }
}
