//
//  ReceiveMainViewController.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-21.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit


protocol ReceiveMainDisplayLogic: class
{
  func displayOnChainAddress(viewModel: ReceiveMain.GenerateOnChain.ViewModel)
  func displayGenerateOnChainFailure(viewModel: ReceiveMain.GenerateOnChain.ViewModel)
}


class ReceiveMainViewController: UIViewController, ReceiveMainDisplayLogic
{
  var interactor: ReceiveMainBusinessLogic?
  var router: (NSObjectProtocol & ReceiveMainRoutingLogic & ReceiveMainDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ReceiveMainInteractor()
    let presenter = ReceiveMainPresenter()
    let router = ReceiveMainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    // Configure the Navigation Bar
    
    
    // Generate a new Address everytime on load
    let request = ReceiveMain.GenerateOnChain.Request()
    interactor?.generateOnChain(request: request)
  }
  
  
  // MARK: Display New On-Chain Address
  
  @IBOutlet weak var qrImageView: UIImageView!
  @IBOutlet weak var addressLabel: UILabel!
  
  func displayOnChainAddress(viewModel: ReceiveMain.GenerateOnChain.ViewModel) {
    DispatchQueue.main.async {
      self.qrImageView.image = viewModel.qrAddressImage
      self.addressLabel.text = viewModel.addressText
      
      if viewModel.addressText != nil {
        self.shareBarButton.isEnabled = true
      } else {
        self.shareBarButton.isEnabled = false
      }
    }
  }
  
  func displayGenerateOnChainFailure(viewModel: ReceiveMain.GenerateOnChain.ViewModel) {
    let alertDialog = UIAlertController(title: viewModel.errTitle, message: viewModel.errMsg, preferredStyle: .alert).addAction(title: "OK", style: .default)
    DispatchQueue.main.async {
      self.present(alertDialog, animated: true, completion: nil)
    }
  }
  
  
  // MARK: Dismiss
  
  @IBAction func closeTapped(_ sender: UIBarButtonItem) {
    router?.routeToWalletMain()
  }
  
  
  // MARK: Share Sheet
  
  @IBOutlet weak var shareBarButton: UIBarButtonItem!
  
  @IBAction func shareTapped(_ sender: UIBarButtonItem) {
    
    if let addressText = addressLabel.text {
      let activityViewController : UIActivityViewController = UIActivityViewController(
        activityItems: [addressText], applicationActivities: nil)
      
      activityViewController.popoverPresentationController?.barButtonItem = sender
      
      activityViewController.excludedActivityTypes = [
        UIActivityType.postToWeibo,
        UIActivityType.print,
        UIActivityType.assignToContact,
        UIActivityType.saveToCameraRoll,
        UIActivityType.addToReadingList,
        UIActivityType.postToFlickr,
        UIActivityType.postToVimeo,
        UIActivityType.postToTencentWeibo,
        UIActivityType(rawValue: "com.apple.reminders.RemindersEditorExtension"),
        UIActivityType(rawValue: "com.apple.mobilenotes.SharingExtension")
      ]
      
      present(activityViewController, animated: true, completion: nil)
    }
  }
  
  
  // MARK: Copying Address to Clipboard
  
  @IBAction func addressCopyTapped(_ sender: UITapGestureRecognizer) {
    
    // Don't do anything if there's no address displayed
    if let addressText = addressLabel.text {
      
      // This is what actually puts the text onto the clipboard
      UIPasteboard.general.string = addressText
      
      // This just shows a brief dialog to let the user know
      SLTextDialogView.show("Copied", on: self.view)
    }
  }
}
