//
//  ReceiveMainModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-21.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ReceiveMain
{
  enum GenerateOnChain
  {
    struct Constants {
      static let qrImageSizeXY: CGFloat = 200.0
    }
    struct Request
    {
    }
    struct Response
    {
      var result: Result<String>  // On Chain Address
    }
    struct ViewModel
    {
      var qrAddressImage: UIImage?
      var addressText: String?
      var errTitle: String?
      var errMsg: String?
    }
  }
}
