//
//  WalletLogInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletLogBusinessLogic
{
  func doSomething(request: WalletLog.Something.Request)
}

protocol WalletLogDataStore
{
  //var name: String { get set }
}

class WalletLogInteractor: WalletLogBusinessLogic, WalletLogDataStore
{
  var presenter: WalletLogPresentationLogic?
  var worker: WalletLogWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WalletLog.Something.Request)
  {
    worker = WalletLogWorker()
    worker?.doSomeWork()
    
    let response = WalletLog.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
