//
//  WalletLogPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletLogPresentationLogic
{
  func presentSomething(response: WalletLog.Something.Response)
}

class WalletLogPresenter: WalletLogPresentationLogic
{
  weak var viewController: WalletLogDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WalletLog.Something.Response)
  {
    let viewModel = WalletLog.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
