//
//  MnemonicExplainInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-18.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MnemonicExplainBusinessLogic
{
  func doSomething(request: MnemonicExplain.Something.Request)
}

protocol MnemonicExplainDataStore
{
  //var name: String { get set }
}

class MnemonicExplainInteractor: MnemonicExplainBusinessLogic, MnemonicExplainDataStore
{
  var presenter: MnemonicExplainPresentationLogic?
  var worker: MnemonicExplainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MnemonicExplain.Something.Request)
  {
    worker = MnemonicExplainWorker()
    worker?.doSomeWork()
    
    let response = MnemonicExplain.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
