//
//  MnemonicConfirmModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-19.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MnemonicConfirm {
  
  struct Constants {
    static let wordsToConfirm = 3
  }
  
  enum GenRandomIndices {
    struct Request {
      var numToGen: Int
    }
    struct Response {
      var wordIndices: [Int]
    }
    struct ViewModel {
      var labelTexts: [String]
    }
  }
  
  enum CheckSeedWords {
    struct Request {
      var seedWords: [String]
    }
    struct Response {
      var areSeedWordsCorrect: [Bool]
    }
    struct ViewModel {
      var checkmarksHidden: [Bool]
      var confirmButtonText: String
      var confirmButtonTextColor: UIColor
      var confirmButtonColor: UIColor
      var confirmButtonShadowColor: UIColor
      var confirmButtonEnable: Bool
    }
  }
  
  enum ConfirmSeedWords {
    struct Request {
      var seedWords: [String]
    }
    struct Response {
      var seedWordsCorrect: Bool
    }
    struct ViewModel {
      var errorTitle: String
      var errorMsg: String
    }
  }
}
