//
//  PayMainViewController.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-28.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayMainDisplayLogic: class {
  
  func updateInvalidity(addr: Bool, amt: Bool, route: Bool)
  func displayConfirmPayment(viewModel: PayMain.ConfirmPayment.ViewModel)
  func displayAddressWarning(viewModel: PayMain.AddressVM)
  func displayAmountWarning(viewModel: PayMain.AmountVM)
  func displayWarning(viewModel: PayMain.WarningVM)
  func displayError(viewModel: PayMain.ErrorVM)
}


class PayMainViewController: UIViewController, PayMainDisplayLogic {
  var interactor: PayMainBusinessLogic?
  var router: (NSObjectProtocol & PayMainRoutingLogic & PayMainDataPassing)?
  
  
  // MARK: IBOutlets
  
  @IBOutlet weak var headerView: SLFormHeaderView!
  @IBOutlet weak var addressEntryView: SLFormEntryView!
  @IBOutlet weak var amountEntryView: SLFormEntryView!
  @IBOutlet weak var descriptionEntryView: SLFormEntryView!
  
  @IBOutlet weak var warningView: UIView!
  @IBOutlet weak var warningLabel: UILabel!
  @IBOutlet weak var sendButton: SLBarButton!
  
  var isAddressInvalid: Bool = false
  var isAmountInvalid: Bool = false
  var isRoutingInvalid: Bool = false
  
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  
  // MARK: Setup
  
  private func setup() {
    
    let viewController = self
    let interactor = PayMainInteractor()
    let presenter = PayMainPresenter()
    let router = PayMainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  
  // MARK: Dismiss
  
  @IBAction func closeCrossTapped(_ sender: UIBarButtonItem) {
    DispatchQueue.main.async {
      self.router?.routeToWalletMain()
    }
  }
  
  
  // MARK: Validity Tracking
  func updateInvalidity(addr: Bool, amt: Bool, route: Bool) {
    isAddressInvalid = addr
    isAmountInvalid = amt
    isRoutingInvalid = route
    
    // Update button state
    if (isAddressInvalid || isAmountInvalid || isRoutingInvalid ||
        !(addressEntryView.textField.text?.isEmpty ?? true) ||
      !(amountEntryView.textField.text?.isEmpty ?? true)) {
      
      sendButton.backgroundColor = UIColor.disabledGray
      sendButton.shadowColor = UIColor.disabledGrayShadow
      sendButton.setTitleColor(UIColor.disabledText, for: .normal)
      
    } else {
      sendButton.backgroundColor = UIColor.medAquamarine
      sendButton.shadowColor = UIColor.medAquamarineShadow
      sendButton.setTitleColor(UIColor.disabledText, for: .normal)
    }
  }
  
  
  // MARK: Send Payment
  
  @IBAction func sendTapped(_ sender: SLBarButton) {
    let request = PayMain.ConfirmPayment.Request(rawAddressString: addressEntryView.textField.text ?? "",
                                                 rawAmountString: amountEntryView.textField.text ?? "")
    interactor?.confirmPayment(request: request)
  }
  
  func displayConfirmPayment(viewModel: PayMain.ConfirmPayment.ViewModel) {
    if let address = viewModel.revisedAddress {
      addressEntryView.textField.text = address
    }
    
    if let amount = viewModel.revisedAmount {
      amountEntryView.textField.text = amount
    }
    
    if let paymentType = viewModel.paymentType {
      switch paymentType {
      case .lightning:
        headerView.iconImageView.image = UIImage(named: "BoltColored")
        headerView.headerLabel.text = "Lightning Payment"
      case .onChain:
        headerView.iconImageView.image = UIImage(named: "ChainColored")
        headerView.headerLabel.text = "On-Chain Payment"
      }
    }
    
    amountEntryView.balanceLabel.text = viewModel.balance
    
    // TODO: fee button color should change based on whether fee is within expected range
    amountEntryView.feeButton.setTitle(viewModel.fee, for: .normal)
    
    if viewModel.goToConfirm {
      DispatchQueue.main.async {
        self.router?.routeToPayConfirm()
      }
    }
  }
   
  
  // MARK: Error Display
  
  func displayAddressWarning(viewModel: PayMain.AddressVM) {
    DispatchQueue.main.async {
      self.addressEntryView.errorLabel.text = viewModel.errMsg
    }
  }
  
  func displayAmountWarning(viewModel: PayMain.AmountVM) {
    DispatchQueue.main.async {
      self.amountEntryView.errorLabel.text = viewModel.errMsg
    }
  }
  
  func displayWarning(viewModel: PayMain.WarningVM) {
    DispatchQueue.main.async {
      if viewModel.errMsg != "" {
        self.warningLabel.text = viewModel.errMsg
        self.warningView.isHidden = false
      } else {
        self.warningLabel.text = ""
        self.warningView.isHidden = true
      }
    }
  }
  
  func displayError(viewModel: PayMain.ErrorVM) {
    let alertDialog = UIAlertController(title: viewModel.errTitle, message: viewModel.errMsg, preferredStyle: .alert).addAction(title: "OK", style: .default)
    DispatchQueue.main.async {
      self.present(alertDialog, animated: true, completion: nil)
    }
  }

}
