//
//  MnemonicDisplayRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-18.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MnemonicDisplayRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MnemonicDisplayDataPassing
{
  var dataStore: MnemonicDisplayDataStore? { get }
}

class MnemonicDisplayRouter: NSObject, MnemonicDisplayRoutingLogic, MnemonicDisplayDataPassing
{
  weak var viewController: MnemonicDisplayViewController?
  var dataStore: MnemonicDisplayDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: MnemonicDisplayViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MnemonicDisplayDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
