//
//  MnemonicDisplayRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-18.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MnemonicDisplayRoutingLogic
{
  func routeToMnemonicConfirm()
}

protocol MnemonicDisplayDataPassing
{
  var dataStore: MnemonicDisplayDataStore? { get }
}

class MnemonicDisplayRouter: NSObject, MnemonicDisplayRoutingLogic, MnemonicDisplayDataPassing
{
  weak var viewController: MnemonicDisplayViewController?
  var dataStore: MnemonicDisplayDataStore?
  
  // MARK: Routing
  
  func routeToMnemonicConfirm()
  {
    let storyboard = UIStoryboard(name: "MnemonicConfirm", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "MnemonicConfirmViewController") as! MnemonicConfirmViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToMnemonicConfirm(source: dataStore!, destination: &destinationDS)
    navigateToMnemonicConfirm(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToMnemonicConfirm(source: MnemonicDisplayViewController, destination: MnemonicConfirmViewController)
  {
    source.present(destination, animated: true, completion: nil)
  }
  
  // MARK: Passing data
  
  func passDataToMnemonicConfirm(source: MnemonicDisplayDataStore, destination: inout MnemonicConfirmDataStore)
  {
    // destination.name = source.name
  }
}
