//
//  WalletBalanceModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WalletBalance {
  
  // MARK: Refresh Balance
  
  enum Refresh {
    struct Request { }
    struct Response {
      var totalBalance: Bitcoin?
      var onChainTotal: Bitcoin?
      var onChainConfirmed: Bitcoin?
      var onChainUnconfirmed: Bitcoin?
      var channelConfirmed: Bitcoin?
      var channelPending: Bitcoin?
    }
    struct ViewModel {
      var totalBalance: String
      var onChainTotal: String
      var onChainConfirmed: String
      var onChainUnconfirmed: String
      var channelConfirmed: String
      var channelPending: String
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
