project 'SwiftLightning.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'SwiftLightning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLightning
  pod 'SwiftProtobuf', '~> 1.0'
  
end
