project 'SwiftLightning.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'SwiftLightning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLightning
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10'
  pod 'CocoaLumberjack/Swift', '~> 3.4.1', :inhibit_warnings => true
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'gRPC-Core', :git => 'https://github.com/mrmage/grpc', :branch => 'fix-cocoapods-swift'
  pod 'SwiftGRPC', :git => 'https://github.com/grpc/grpc-swift', :inhibit_warnings => true
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwiftRangeSlider'
  
end
