//
//  ChannelConfirmPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-25.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelConfirmPresentationLogic
{
  func presentRefreshAll<C: Currency>(response: ChannelConfirm.RefreshAll.Response<C>)
}


class ChannelConfirmPresenter: ChannelConfirmPresentationLogic
{
  weak var viewController: ChannelConfirmDisplayLogic?
  
  // MARK: Refresh All
  
  func presentRefreshAll<C: Currency>(response: ChannelConfirm.RefreshAll.Response<C>) {

    let viewModel = ChannelConfirm.RefreshAll.ViewModel(fundingAmt: response.fundingAmt.formattedInSatoshis(),
                                                        refFundingAmt: "",
                                                        nodePubKey: response.nodePubKey,
                                                        nodeIP: response.nodeIP,
                                                        nodePort: String(response.nodePort),
                                                        initPayAmt: response.initPayAmt.formattedInSatoshis(),
                                                        refInitPayAmt: "",
                                                        confSpeed: response.confSpeed.description,
                                                        canPayAmt: response.canPayAmt.formattedInSatoshis(),
                                                        canRcvAmt: response.canPayAmt.formattedInSatoshis(),
                                                        fee: "")
    
    viewController?.displayRefreshAll(viewModel: viewModel)
  }
}
