//
//  NeutrinoPeersInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NeutrinoPeersBusinessLogic {
  func fetchCurrentPeers(request: NeutrinoPeers.CurrentPeers.Request)
}


protocol NeutrinoPeersDataStore {
  //var name: String { get set }
}


class NeutrinoPeersInteractor: NeutrinoPeersBusinessLogic, NeutrinoPeersDataStore {
  var presenter: NeutrinoPeersPresentationLogic?
  
  
  // MARK: Current Peers
  
  func fetchCurrentPeers(request: NeutrinoPeers.CurrentPeers.Request) {
    
    do {
      // Read LND.conf and find all instances of addrpeers
      let peerAddrs = try LNManager.findNeutrinoPeers(andReplaceWith: nil)
      
      
      
    } catch {
      
    }
    let response = NeutrinoPeers.CurrentPeers.Response()
    presenter?.presentSomething(response: response)
  }
}
