//
//  NeutrinoPeersModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NeutrinoPeers {
  
  // MARK: Current Peers
  
  enum CurrentPeers {
    struct Request { }
    struct Response {
      var result: Result<[String]>
    }
    struct ViewModel {
      var peers: [String]
    }
  }
  
  enum WritePeers {
    struct Request {
      var peers: [String]
    }
    struct Response {
      var result: Result<Void>
    }
    struct ViewModel {
      var dialogTitle: String
      var dialogMsg: String
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
