//
//  NeutrinoPeersPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NeutrinoPeersPresentationLogic
{
  func presentSomething(response: NeutrinoPeers.Something.Response)
}

class NeutrinoPeersPresenter: NeutrinoPeersPresentationLogic
{
  weak var viewController: NeutrinoPeersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NeutrinoPeers.Something.Response)
  {
    let viewModel = NeutrinoPeers.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
