//
//  SettingsMainPresenter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsMainPresentationLogic
{
  func presentSomething(response: SettingsMain.Something.Response)
}

class SettingsMainPresenter: SettingsMainPresentationLogic
{
  weak var viewController: SettingsMainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SettingsMain.Something.Response)
  {
//    let viewModel = SettingsMain.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
