//
//  SettingsMainInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-11.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsMainBusinessLogic
{
  func doSomething(request: SettingsMain.Something.Request)
}

protocol SettingsMainDataStore
{
  //var name: String { get set }
}

class SettingsMainInteractor: SettingsMainBusinessLogic, SettingsMainDataStore
{
  var presenter: SettingsMainPresentationLogic?
  var worker: SettingsMainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SettingsMain.Something.Request)
  {
    worker = SettingsMainWorker()
    worker?.doSomeWork()
    
    let response = SettingsMain.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
