//
//  WalletMainInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletMainBusinessLogic
{
  func doSomething(request: WalletMain.Something.Request)
}

protocol WalletMainDataStore
{
  //var name: String { get set }
}

class WalletMainInteractor: WalletMainBusinessLogic, WalletMainDataStore
{
  var presenter: WalletMainPresentationLogic?
  var worker: WalletMainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WalletMain.Something.Request)
  {
    worker = WalletMainWorker()
    worker?.doSomeWork()
    
    let response = WalletMain.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
