//
//  UnlockAppRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UnlockAppRoutingLogic
{
  func routeToWalletThruRoot()
}

protocol UnlockAppDataPassing
{
  var dataStore: UnlockAppDataStore? { get }
}

class UnlockAppRouter: NSObject, UnlockAppRoutingLogic, UnlockAppDataPassing
{
  weak var viewController: UnlockAppViewController?
  var dataStore: UnlockAppDataStore?
  
  
  // MARK: Routing
  
  func routeToWalletThruRoot() {
    // Take a detour. Ask the RootViewController to do the work
    AppDelegate.rootViewController.dismiss(animated: false) {
      AppDelegate.rootViewController.goWalletNavigation()
    }
  }
  
  
  // MARK: Navigation
  
}
