//
//  UnlockAppInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UnlockAppBusinessLogic
{
  func doSomething(request: UnlockApp.Something.Request)
}

protocol UnlockAppDataStore
{
  //var name: String { get set }
}

class UnlockAppInteractor: UnlockAppBusinessLogic, UnlockAppDataStore
{
  var presenter: UnlockAppPresentationLogic?
  var worker: UnlockAppWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UnlockApp.Something.Request)
  {
    worker = UnlockAppWorker()
    worker?.doSomeWork()
    
    let response = UnlockApp.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
