//
//  UnlockAppInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-04-20.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UnlockAppBusinessLogic {
  func checkPassword(request: UnlockApp.CheckPassword.Request)
}

protocol UnlockAppDataStore { }


class UnlockAppInteractor: UnlockAppBusinessLogic, UnlockAppDataStore
{
  var presenter: UnlockAppPresentationLogic?
  
  // MARK: Check Password
  
  func checkPassword(request: UnlockApp.CheckPassword.Request)
  {
    do {
      try LNServices.unlockWallet(walletPassword: request.passwordText) { (result) in
        do {
          try result()  // Does not return. But if error free, that means password is correct
          let response = UnlockApp.CheckPassword.Response(errorDescription: nil)
          self.presenter?.presentCheckResult(response: response)
        } catch {
          let response = UnlockApp.CheckPassword.Response(errorDescription: error.localizedDescription)
          self.presenter?.presentCheckResult(response: response)
        }
      }
    } catch {
      let response = UnlockApp.CheckPassword.Response(errorDescription: error.localizedDescription)
      presenter?.presentCheckResult(response: response)
    }
  }
}
