//
//  WalletInfoModels.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WalletInfo {
  
  // MARK: Refresh
  
  enum Refresh {
    struct Request { }
    struct Response {
      var result: Result<LNDInfo>
      var networkInfo: LNDNetworkInfo?
    }
    struct ViewModel {
      var idPubKey: String
      var alias: String
      var pendingChs: String
      var activeChs: String
      var numPeers: String
      var numNodes: String?
      var numChannels: String?
      var blockHeight: String
      var blockHash: String
      var bestHdrTimestamp: String
      var syncedChain: String
    }
  }
  
  struct ErrorVM {
    var errTitle: String
    var errMsg: String
  }
}
