//
//  WalletInfoInteractor.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-13.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletInfoBusinessLogic {
  func refresh(request: WalletInfo.Refresh.Request)
}

protocol WalletInfoDataStore {
  //var name: String { get set }
}

class WalletInfoInteractor: WalletInfoBusinessLogic, WalletInfoDataStore {
  var presenter: WalletInfoPresentationLogic?
  //var name: String = ""
  
  // MARK: Refresh
  
  func refresh(request: WalletInfo.Refresh.Request) {
    LNServices.getInfo { (responder) in
      do {
        let info = try responder()
        
        let result = Result<LNDInfo>.success(info)
        let response = WalletInfo.Refresh.Response(result: result)
        self.presenter?.presentRefresh(response: response)
      } catch {
        let result = Result<LNDInfo>.failure(error)
        let response = WalletInfo.Refresh.Response(result: result)
        self.presenter?.presentRefresh(response: response)
      }
    }
  }
}
