//
//  ChannelDetailsRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-04.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChannelDetailsRoutingLogic
{
  func routeToWalletMain()
}

protocol ChannelDetailsDataPassing
{
  var dataStore: ChannelDetailsDataStore? { get }
}

class ChannelDetailsRouter: NSObject, ChannelDetailsRoutingLogic, ChannelDetailsDataPassing
{
  weak var viewController: ChannelDetailsViewController?
  var dataStore: ChannelDetailsDataStore?
  
  // MARK: Routing
  
  func routeToWalletMain() {
    //    let destinationVC = viewController! as! WalletMainViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToWalletMain(source: dataStore!, destination: &destinationDS)
    navigateToWalletMain(source: viewController!)
  }
  

  // MARK: Navigation
  
  func navigateToWalletMain(source: ChannelDetailsViewController) {
    guard let navigationController = source.navigationController else {
      SLLog.assert("\(type(of: source)).navigationController = nil")
      return
    }
    navigationController.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToWalletMain(source: ChannelOpenDataStore, destination: inout WalletMainDataStore) { }
}
