//
//  CameraMainRouter.swift
//  SwiftLightning
//
//  Created by Howard Lee on 2018-05-02.
//  Copyright (c) 2018 BiscottiGelato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CameraMainRoutingLogic
{
  func routeToPrevious()
}

protocol CameraMainDataPassing
{
  var dataStore: CameraMainDataStore? { get }
}

class CameraMainRouter: NSObject, CameraMainRoutingLogic, CameraMainDataPassing
{
  weak var viewController: CameraMainViewController?
  var dataStore: CameraMainDataStore?
  
  // MARK: Routing
  
  func routeToPrevious()
  {
    //let destinationVC = viewController! as! CameraMainViewController
    //    let destinatoinDS = destinationVC.router!.dataStore!
    //    passDataToWalletMain(source: dataStore!, destination: &destinationDS)
    navigateToPrevious(source: viewController!)
  }
  
  
  // MARK: Navigation
  
  func navigateToPrevious(source: CameraMainViewController) {
    guard let navigationController = source.navigationController else {
      SLLog.assert("\(type(of: source)).navigationController = nil")
      return
    }
    navigationController.popViewController(animated: true)
  }
}
